### ISSUE TITLE
pip install on windows no longer works

### ISSUE THREAD

**Issue by EricSidorov** [wolfSSL/wolfcrypt-py#55] opened 2023-04-18 11:06 UTC
on Windows 11, with all perquisites installed (VS build tools, git, cmake). Python version 3.11 (but reproduced with 3.9 as well)
`pip3.11 -v install wolfcrypt`
Fails (see attached log). However:
`pip3.11 -v install wolfcrypt==5.3.0post0 `
Succeeds
[wolfcrypt_pip_install_issue.log](https://github.com/wolfSSL/wolfcrypt-py/files/11260985/wolfcrypt_pip_install_issue.log)

**Comment by danielinux** [comment] 2023-04-19 10:57
This should be fixed in #56. We are preparing the new release and the new python package should be installed correctly. I suggest keeping the issue open until confirmed.

**Comment by lealem47** [comment] 2023-05-03 19:13
Hi @EricSidorov, have you been able to check if your issue is resolved in wolfcrypt-py v5.6.0?

**Comment by ConradGroth** [comment] 2023-09-05 13:47
I just tried to build v5.6.0-stable locally on Windows 10 with `python setup.py sdist` and it failed within the user_settings_asm.sh step. I found out, that this was actually fixed in wolfssl itself for v5.6.2-stable. So I updated the value of `__wolfssl_version__` in the file `wolfcrypt/_version.py` to `v5.6.3-stable` and now my local Windows build is fine.

**Comment by lealem47** [comment] 2023-09-05 15:40
Hi @ConradGroth,

Glad you got it working. What you described is expected since the following fix was added in wolfSSL v5.6.2 https://github.com/wolfSSL/wolfssl/pull/6322.

Closing this for issue for now but thank you for the report.

**Closed by lealem47** 2023-09-05 15:40 UTC
